name: "Process Julia Coverage"
description: "Calculate coverage and generate a lcov file"
author: "Heptazhou"

branding:
  icon: "settings"
  color: "gray-dark"

inputs:
  dirs:
    default: "src"
    description: "List of directories to look for coverage, separated by endl or colon (e.g., `src:dir1:dir2`)"
    required: false
  file:
    default: "lcov.info"
    description: "Path of the lcov file to use. Will generate one if missing."
    required: false
  keep:
    default: "true"
    description: "If so, use an existing lcov file (`true` or `false`)."
    required: false
  skip:
    default: "false"
    description: "Skip any missing directory (`true` or `false`)."
    required: false

runs:
  using: "composite"
  steps:
    - run: julia --color=yes "$GITHUB_ACTION_PATH"/main.jl
      shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.dirs }}
        INPUT_LCOV_FILE: ${{ inputs.file }}
        INPUT_LCOV_KEEP: ${{ inputs.keep }}
        INPUT_SKIP_MISS: ${{ inputs.skip }}
