name: "Process Julia Coverage"
description: "Calculate coverage and generate a lcov file"
author: "Heptazhou"

branding:
  icon: "settings"
  color: "gray-dark"

inputs:
  directory:
    default: "src"
    description: "Colon-separated list of directories to look for coverage (e.g., `src:examples`)"
    required: false
  file:
    default: "lcov.info"
    description: "Path of lcov file to use. Will try to generate it if not exists."
    required: false
  force:
    default: "false"
    description: "Force to generate a new lcov file (`true` or `false`)."
    required: false

runs:
  using: "composite"
  steps:
    - run: julia --color=yes "$GITHUB_ACTION_PATH"/main.jl
      shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_FILE_LCOV: ${{ inputs.file }}
        INPUT_FORCE: ${{ inputs.force }}
